version: "3"
services:
  norber_api_php:
    container_name: norber_api_php
    build:
      context: "./.docker"
      dockerfile: Dockerfile
    ports:
      - "9003:9002" # fpm
      - "5174:5174" # vite
    volumes:
      - "./.:/var/www/html"
